package rules.labelling;

import org.drools.tx.model.*;

declare Transaction
    @role(event)
end

query getUnlabelledTXs( )
    $tx: Transaction( labels.size == 0 ) 
       
end

rule "Sharing Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( quantity > 1 ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("sharing")
        };
        modify($tx){};
end

rule "Coke Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches "(?i).*coca.*" || itemDescription matches "(?i).*pepsi.*" || itemDescription matches "(?i).*cola.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("cold drink")
        };
        modify($tx){};
end

rule "Juice Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches "(?i).*juice.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("cold drink")
        };
        modify($tx){};
end

rule "Lemonade Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches "(?i).*lemonade.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("cold drink")
        };
        modify($tx){};
end


rule "Beer Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*beer.*" || itemDescription matches  "(?i).*stella.*" || itemDescription matches  "(?i).*pint.*") 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("alcohol"),
            addLabel("beer"),
            addLabel("cold drink")
        };
        modify($tx){};
end

rule "Whiskey Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*daniels.*" || itemDescription matches  "(?i).*whiskey.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("alcohol"),
            addLabel("whiskey"),
            addLabel("spirit"),
            addLabel("cold drink")
        };
        modify($tx){};
end



rule "Cider Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*cider.*" || itemDescription matches  "(?i).*strongbow.*") 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("alcohol"),
            addLabel("cider"),
            addLabel("cold drink")
        };
        modify($tx){};
end

rule "Vodka Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*vodka.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("alcohol"),
            addLabel("vodka"),
            addLabel("spirit"),
            addLabel("cold drink")
        };
        modify($tx){};
end

rule "Tequila Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*tequila.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("alcohol"),
            addLabel("spirit"),
            addLabel("tequila"),
            addLabel("cold drink")
        };
        modify($tx){};
end

rule "VK Cocktails Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  ".*VK.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("alcohol"),
            addLabel("cocktail"),
            addLabel("cold drink")
        };
        modify($tx){};
end


rule "Coffee Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*coffee.*" || itemDescription matches  "(?i).*latte.*" || itemDescription matches  "(?i).*cappucino.*"  ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("coffee"),
            addLabel("hot drink")
        };
        modify($tx){};
end

rule "Tea Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*tea.*" ) 
        $tx: Transaction( lines contains $l )
    then
        modify($l){
            addLabel("tea"),
            addLabel("hot drink")
        };
        modify($tx){};
end

rule "Sandwich Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*sandwich.*" )
        $tx: Transaction( lines contains $l ) 
    then
        modify($l){
            addLabel("food"),
            addLabel("sandwich")
        };
        modify($tx){};
end

rule "PIZZA Tx"
    no-loop true
    lock-on-active true
    when
        $l: Line( $desc: itemDescription matches  "(?i).*pizza.*" )
        $tx: Transaction( lines contains $l ) 
    then
        modify($l){
            addLabel("food"),
            addLabel("pizza")
        };
        modify($tx){};
end


