package rules.labelling;

import org.drools.tx.model.*;



global String out;

rule "new transaction"
    when
        $tx: Transaction()
    then
        System.out.println("New TX here: "+$tx + "  out -> " + out);
end

/*

declare Transaction
    @role event
end


query getTxForLabel(String $labeName)
    $l: Label( name == $labelName )
end

query getTxForLabelByTill(String $categoryName, String tillId)
    $t: Trasaction( tillTransactionId == tillId)
    $l: Label( name == $categoryName, txs contains $t) 
end

rule "New Label"
    when
         $t: Trasaction($b: basket)
         $l: Line( $desc: itemDescription ) 
         Basket(this == $b,  lines contains $l)
         not(Category( name == "Beer"))
    then
        Label l = new Label($desc);
        insertLogical(l);
        modify($t){
            addLabel(l);
        };
        
end

rule "Existing Label"
    lock-on-active true
    when
         $t: Trasaction( $b: basket )
         $l: Line( $desc: itemDescription ) 
         Basket(this == $b,  lines contains $l )
         $l: Label( name == $desc )
    then
        modify($t){
            addLabel($l);
        };   
end*/


